backend:
  name: git-gateway
  branch: master

media_folder: "static/img"

collections:
  - name: "workshops"
    label: "HEX Workshops"
    folder: "src/workshops"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Start Time", name: "time", widget: "datetime"}
      - label: "Teachers"
        name: "teachers"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Profile Picture", name: "img", widget: "image"}